export const storyData = [
  {
    position: 1,
    title: "There Are No Bugs, Just TODOs",
    site: "almad.blog",
    points: 64,
    author: "Almad",
    date: "1 hour ago",
    comments: 14,
  },
  {
    position: 2,
    title: "SimRefinery Recovered",
    site: "obscuritory.com",
    points: 497,
    author: "velmu",
    date: "10 hours ago",
    comments: 86,
  },
  {
    position: 3,
    title: "Why Is the Human Brain So Efficient? (2018)",
    site: "nautil.us",
    points: 111,
    author: "rcshubhadeep",
    date: "5 hours ago",
    comments: 72,
  },
  {
    position: 4,
    title: "Mental Wealth",
    site: "jjbeshara.com",
    points: 144,
    author: "imartin2k",
    date: "6 hours ago",
    comments: 102,
  },
  {
    position: 5,
    title:
      "People try to do right by each other, no matter the motivation, study finds",
    site: "phys.org",
    points: 77,
    author: "pseudolus",
    date: "7 hours ago",
    comments: 54,
  },
  {
    position: 6,
    title: "Ask HN: How do I reach making $1-1.5k/mo in 13 months?",
    points: 198,
    author: "noddly",
    date: "2 hours ago",
    comments: 129,
  },
  {
    position: 7,
    title: "Julia as a CLI Calculator",
    site: "krasjet.com",
    points: 84,
    author: "krjt",
    date: "6 hours ago",
    comments: 56,
  },
  {
    position: 8,
    title: "First photo of HS2 tunnel boring machines",
    site: "ianvisits.co.uk",
    points: 74,
    author: "edward",
    date: "8 hours ago",
    comments: 97,
  },
  {
    position: 9,
    title: "High-Speed Pool and Billiards Video Clips",
    site: "colostate.edu",
    points: 21,
    author: "Tomte",
    date: "3 hours ago",
    comments: 2,
  },
  {
    position: 10,
    title: "A History of Clojure [pdf]",
    site: "clojure.org",
    points: 563,
    author: "puredanger",
    date: "22 hours ago",
    comments: 315,
  },
  {
    position: 11,
    title:
      "Germany, France launch Gaia-X platform in bid for ‘tech sovereignty’",
    site: "politico.eu",
    points: 151,
    author: "tpush",
    date: "6 hours ago",
    comments: 356,
  },
  {
    position: 12,
    title:
      "Google2Csv is a simple Google scraper that saves the results on a CSV file",
    site: "github.com",
    points: 10,
    author: "panos_sa",
    date: "1 hour ago",
    comments: 3,
  },
  {
    position: 13,
    title: "Why So Many Police Are Handling the Protests Wrong",
    site: "themarshallproject.org",
    points: 38,
    author: "epistasis",
    date: "57 minutes ago",
    comments: 20,
  },
  {
    position: 14,
    title:
      "WeChat permanently closes account after user sets CCP-offensive password",
    site: "twitter.com",
    points: 172,
    author: "drevil-v2",
    date: "2 hours ago",
    comments: 82,
  },
  {
    position: 15,
    title:
      "Synthetic red blood cells mimic natural ones, and have new abilities",
    site: "acs.org",
    points: 78,
    author: "headalgorithm",
    date: "13 hours ago",
    comments: 14,
  },
  {
    position: 16,
    title: "Julialang Antipatterns",
    site: "ucc.asn.au",
    points: 40,
    author: "ViralBShah",
    date: "8 hours ago",
    comments: 1,
  },
  {
    position: 17,
    title: "Ask HN: How to Disagree with the Rest of Management?",
    points: 9,
    author: "anonymous_smile",
    date: "1 hour ago",
    comments: 14,
  },
  {
    position: 18,
    title:
      "Signal app downloads spike as US protesters seek message encryption",
    site: "qz.com",
    points: 392,
    author: "pera",
    date: "12 hours ago",
    comments: 307,
  },
  {
    position: 19,
    title: "The Beauty of Unix Pipelines",
    site: "prithu.xyz",
    points: 561,
    author: "0x4FFC8F",
    date: "19 hours ago",
    comments: 332,
  },
  {
    position: 20,
    title:
      "Ask HN: Have you ever gone without a computer or phone for an extended period?",
    points: 120,
    author: "luddite99",
    date: "12 hours ago",
    comments: 131,
  },
  {
    position: 21,
    title: "Kids and Time",
    site: "jefftk.com",
    points: 38,
    author: "luu",
    date: "7 hours ago",
    comments: 28,
  },
  {
    position: 22,
    title: "Open source 5G core network",
    site: "github.com",
    points: 13,
    author: "polymorph1sm",
    date: "5 hours ago",
    comments: 0,
  },
  {
    position: 23,
    title: "Ask HN: Which Coursera courses/specializations you recommend?",
    points: 12,
    author: "quotz",
    date: "1 hour ago",
    comments: 6,
  },
  {
    position: 24,
    title: "Containers from first principles",
    site: "fzakaria.com",
    points: 69,
    author: "setheron",
    date: "12 hours ago",
    comments: 9,
  },
  {
    position: 25,
    title:
      "Ask HN: Are my expectations on code quality and professionalism too high?",
    points: 150,
    author: "veggiepulse",
    date: "5 hours ago",
    comments: 184,
  },
  {
    position: 26,
    title: "Words that don't translate into English",
    site: "theguardian.com",
    points: 64,
    author: "tintinnabula",
    date: "14 hours ago",
    comments: 186,
  },
  {
    position: 27,
    title:
      "The Story Behind The Unmarked Federal Agents Occupying Washington, D.C",
    site: "politico.com",
    points: 60,
    author: "Kapura",
    date: "1 hour ago",
    comments: 13,
  },
  {
    position: 28,
    title: "The Go Compiler Needs to Be Smarter",
    site: "lemire.me",
    points: 141,
    author: "hactually",
    date: "14 hours ago",
    comments: 86,
  },
  {
    position: 29,
    title: "Homoiconicity Revisited",
    site: "expressionsofchange.org",
    points: 37,
    author: "vanschelven",
    date: "10 hours ago",
    comments: 34,
  },
  {
    position: 30,
    title: "macOS in QEMU in Docker",
    site: "github.com",
    points: 460,
    author: "mjtlittle",
    date: "21 hours ago",
    comments: 173,
  },
];
